import Head from "next/head";

export default function About() {
 
  return (
    <>
      <Head>
        <title>Onlene book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <h1>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Laboriosam ipsum, nesciunt sint rerum voluptas porro molestiae atque placeat blanditiis voluptates, sunt provident minus, obcaecati fugit maiores similique et fuga asperiores.</h1>
      </main>
    </>
  );
}
