import Section from "@/components/section/section";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useGetAllProductMutation } from "./api/getAllproduct";
import { useDispatch } from "react-redux";
import { setStoreData } from "@/context/state";

export default function Home() {
  const dispatch = useDispatch();
  const router = useRouter();
  const crypto = require("crypto");
  const [getAllProduct, { isLoading, error, data }] =
    useGetAllProductMutation();

  const userDataString =
    typeof window !== "undefined" ? localStorage.getItem("user") : null;
  const userData = userDataString ? JSON.parse(userDataString) : null;

  const getAllBook = async (userData: any) => {
    console.log(userData);
    //  cripto js run

    function generateMD5Sign(method: string, url: string, userSecret: string) {
      const inputString = method + url + userSecret;
      return crypto.createHash("md5").update(inputString).digest("hex");
    }
    const method = "GET";
    const url = "/books";
    const userSecret = userData?.secret;

    const md5Sign = generateMD5Sign(method, url, userSecret as string);

    //  tray

    try {
      const response = await getAllProduct({
        key: userData?.key,
        sign: md5Sign,
      });
      if ("data" in response) {
        console.log(44, response.data);
        dispatch(setStoreData(response.data.data));
      } else {
        if (response.error) {
          console.log("malumot olishta xatolik");
        }
      }
    } catch (error) {
      console.log(78, error);
    } finally {
    }
  };

  useEffect(() => {
    if (!userData) {
      router.push("/login");
    } else {
      getAllBook(userData);
    }
  }, []);

  return (
    <div>
      <Head>
        <title>Onlene book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Section.Home />
    </div>
  );
}
