import Section from "@/components/section/section";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useGetAllProductMutation } from "./api/getAllproduct";
import { useDispatch } from "react-redux";
import { setStoreData } from "@/context/state";

export default function Home() {
  const dispatch = useDispatch();
  const router = useRouter();
  const crypto = require("crypto");
  const [getAllProduct, { isLoading, error, data }] =
    useGetAllProductMutation();
  interface Superhero {
    name: string;
    secret: string;
    key: string;
  }

  const [user, setUser] = useState<Superhero | null>(null);

  const getAllBook = async (user: Superhero | null) => {
    //  cripto js run

    console.log(user);

    function generateMD5Sign(method: string, url: string, userSecret: string) {
      const inputString = method + url + userSecret;
      return crypto.createHash("md5").update(inputString).digest("hex");
    }
    const method = "GET";
    const url = "/books";
    const userSecret = "AdimJhons";

    const md5Sign = generateMD5Sign(method, url, userSecret as string);

    //  tray

    try {
      const response = await getAllProduct({
        key: "Adims",
        sign: md5Sign,
      });
      if ("data" in response) {
        console.log(44, response.data);
        dispatch(setStoreData(response.data.data));
      } else {
        if (response.error) {
          console.log("malumot olishta xatolik");
        }
      }
    } catch (error) {
      console.log(78, error);
    } finally {
    }
  };

  useEffect(() => {
    function getCookie(key: string) {
      const name = key + "=";
      const decodedCookie = decodeURIComponent(document.cookie);
      const cookieArr = decodedCookie.split(";");
      for (let i = 0; i < cookieArr.length; i++) {
        let cookie = cookieArr[i];
        while (cookie.charAt(0) == " ") {
          cookie = cookie.substring(1);
        }
        if (cookie.indexOf(name) == 0) {
          return JSON.parse(cookie.substring(name.length, cookie.length));
        }
      }
      return null;
    }
    if (getCookie("user")) {
      setUser(getCookie("user"));
    } else {
      router.push("/login");
    }
    getAllBook(user);
  }, []);

  return (
    <div>
      <Head>
        <title>Onlene book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Section.Home />
    </div>
  );
}
