import Section from "@/components/section/section";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Onlene book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Section.Home />
    </div>
  );
}
