import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Onlene book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Pariatur odit
        facilis, blanditiis nesciunt dolorum ex reiciendis ratione accusantium
        magni totam fuga nobis, rem molestias culpa perferendis dolorem, ipsam
        eveniet illum?z
      </h1>
    </div>
  )
}
