import Section from "@/components/section/section";
import Head from "next/head";

export default function Register() {
  return (
    <>
      <Head>
        <title>Book market</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Section.Register />
      </main>
    </>
  );
}
